collections:
  - name: nginxinc.nginx_controller
    version: "3.9.0"
  - name: nginxinc.nginx_core
    version: "0.3.0"
  - name: azure.azcollection
    version: "1.4.0"
  - name: kubernetes.core
    version: "2.0.2"
