---
- hosts: localhost
  become: no
  gather_facts: no
  vars:

  collections:
    - kubernetes.core

  tasks:

    - name: Create monitoring namespace
      kubernetes.core.k8s:
        name: monitoring
        api_version: v1
        kind: Namespace
        state: present

    - name: Setup RBAC
      kubernetes.core.k8s:
        state: present
        src: manifests/rbac.yaml
