---
- hosts: localhost
  become: no
  gather_facts: no
  vars:

  collections:
    - kubernetes.core

  tasks:

    - name: Create Grafana DataSource
      kubernetes.core.k8s:
        name: grafana-datasources
        namespace: monitoring
        api_version: v1
        kind: ConfigMap
        state: present
        definition:
          data:
            prometheus.yml: |-
              apiVersion: 1
              datasources:
                - access: proxy
                  editable: true
                  name: Prometheus
                  orgId: 1
                  type: prometheus
                  url: http://prometheus-service.monitoring:9090
                  version: 1

    - name: Create Grafana Dash Provider
      kubernetes.core.k8s:
        api_version: v1
        kind: ConfigMap
        name: grafana-dash-providers
        namespace: monitoring
        definition:
          data:
            ds_prometheus.yml: |-
              apiVersion: 1
              providers:
                - name: 'Prometheus'
                  orgId: 1
                  folder: ''
                  type: file
                  disableDeletion: false
                  editable: true
                  options:
                    path: /dashboards
                  
    - name: Upload Grafana Dashboards
      kubernetes.core.k8s:
        state: present
        src: manifests/dashboards.yaml

