---
- hosts: localhost
  become: no
  gather_facts: no
  vars:

  collections:
    - kubernetes.core

  tasks:

    - name: Create Prometheus Config
      kubernetes.core.k8s:
        state: present
        src: manifests/prometheus.yaml

