---
- hosts: localhost
  become: no
  gather_facts: no
  vars:

  collections:
    - kubernetes.core

  tasks:

    - name: Prometheus Deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Deployment
          metadata:
            name: prometheus-deployment
            namespace: monitoring
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: prometheus-server
            template:
              metadata:
                labels:
                  app: prometheus-server
              spec:
                containers:
                  - name: prometheus
                    image: prom/prometheus:v2.26.0
                    args:
                      - "--config.file=/etc/prometheus/prometheus.yml"
                      - "--storage.tsdb.path=/prometheus/"
                    ports:
                      - containerPort: 9090
                    volumeMounts:
                      - name: prometheus-config-volume
                        mountPath: /etc/prometheus/
                      - name: prometheus-storage-volume
                        mountPath: /prometheus/
                volumes:
                  - name: prometheus-config-volume
                    configMap:
                      defaultMode: 420
                      name: prometheus-server-conf
    
                  - name: prometheus-storage-volume
                    emptyDir: {}
    
    - name: Prometheus Service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: prometheus-service
            namespace: monitoring
            annotations:
                prometheus.io/scrape: 'true'
                prometheus.io/path:   /metrics
                prometheus.io/port:   '9090'

          spec:
            selector:
              app: prometheus-server
            type: ClusterIP
            clusterIP: None
            ports:
              - name: http
                port: 9090
                targetPort: 9090
                protocol: TCP

