---
- hosts: localhost
  become: no
  gather_facts: no
  vars:

  collections:
    - kubernetes.core

  tasks:

    - name: debug
      debug:
        msg: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"

    - name: Create monitoring namespace
      kubernetes.core.k8s:
        name: monitoring
        api_version: v1
        kind: Namespace
        state: present

