---
- hosts: nginx
  become: no
  gather_facts: no

  collections:
    - nginxinc.nginx_controller

  tasks:

    - name: Retrieve the NGINX Controller auth token
      include_role:
        name: nginx_controller_generate_token

    - name: Get controller api key for agent registration
      uri:
        url: "https://{{ nginx_controller_fqdn }}/api/v1/platform/global"
        method: "GET"
        return_content: yes
        status_code: 200
        validate_certs: false
        headers:
          Cookie: "{{nginx_controller_auth_token}}"
      register: ctrl_globals

    - name: Configure the location
      include_role:
        name: nginxinc.nginx_controller_location
      vars:
        nginx_controller_location:
          metadata:
            name:  azure-uk
            displayName:  "Azure UK"
          desiredState:
            type: OTHER_LOCATION

    - name: Register NGINX with Controller
      include_role:
        name: nginx_controller_agent
      vars:
        nginx_controller_api_key: "{{ ctrl_globals.json.currentStatus.agentSettings.apiKey }}"
        nginx_controller_location: azure-uk

